<?php

namespace Tests\Feature\User;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setUpUser();
    }

    public function test_database_has_default_user()
    {
        $users = User::where('email', 'admin@demo.com')->get();

        $this->assertCount(1, $users);
    }

    public function testUserCanUpdateHisProfile()
    {
        $this->json('POST', '/api/updateProfile',
            [
                'name' => 'Reza',
                'family' => 'Labbafi',
                'company_name' => 'RezaCo',
            ])
            ->assertStatus(201);

    }

    public function testVerifyTokenWorksWell()
    {
        $this->json('POST', '/api/verify_token')
            ->assertStatus(202);
    }


}
